-- The database backstop under "bill a visit once". (T41 BLOCKER)
--
-- T41 raced POST /api/visits/:id/invoice and got two 201s: 5 of 5 two-way races double-billed, a
-- four-way race produced three invoices, and twice the pair SHARED AN INVOICE NUMBER (INV-00061,
-- INV-00070). The visit links only the last one, so the others sit in AR for ever.
--
-- The route fix is the real one: the whole handler now runs in a transaction, locks the visit row
-- with SELECT … FOR UPDATE and re-checks invoice_id inside the lock. The report asked for four
-- things, and this is the constraint that makes one of them true in the DATABASE rather than only
-- in the code path that happens to be correct today:
--
--   one visit bills once        unique on visit.invoice_id
--
-- WHY A PARTIAL INDEX. visit.invoice_id is null for every unbilled visit, and there are thousands of
-- those; a plain unique index treats nulls as distinct in Postgres so it would work, but
-- WHERE … IS NOT NULL says the intent and keeps the index to the billed rows.
--
--
-- TWO THINGS ABOUT THIS FILE THAT WERE WRONG UNTIL T58d, BOTH OF THEM EXPENSIVE.
--
-- 1. THIS MIGRATION COULD NOT BE APPLIED AT ALL. The comment that used to sit here explained the
--    statement-separator convention and, in doing so, wrote the separator out in full. Drizzle cuts
--    a migration file wherever that text appears and has no idea it is inside a comment, so it cut
--    this file mid-sentence and handed Postgres the second half: a backtick. vettest's log, on every
--    boot from 2026-10-03 to 2026-10-07:
--
--      error: syntax error at or near "`"
--      [migrate] Connection failed, retrying in 10s...      ← it was not the connection
--      [migrate] Failed after 20 attempts
--
--    A run is one transaction, so nothing from here on applied: not this index, not
--    warranty_claim.job_id, not the duplicate-invoice heal. INV-00053 survived three deploys that
--    each shipped a fix for it. scripts/check-migration-statements-parse.ts is the guard, and the
--    separator is now described rather than reproduced.
--
-- 2. THE INVOICE-NUMBER INDEX IS NOT BUILT HERE ANY MORE. It used to be, and on a tenant that
--    already had a duplicate number it could never succeed: CREATE UNIQUE INDEX cannot be built over
--    rows that already violate it. The heal lives in 0034, which renumbers the duplicated drafts —
--    so the index has to be created there, AFTER the heal, or the run dies before the heal is
--    reached. One rule, one place: 0034 owns invoice_company_number_live_unique_idx.
-- 3. AND THE COLUMN IT INDEXES HAS TO EXIST. Found the moment the test harness was made to FAIL on a
--    migration error instead of logging it: `column "invoice_id" does not exist`.
--
--    `visit` is created in 0016_vet_domain.sql and has never had an invoice_id. db/schema.ts
--    declares it, so `drizzle-kit push --force` in the start command adds it on every boot — which
--    is why the column is there on a live tenant and why nobody noticed. But the migration history
--    on its own cannot build the schema it indexes, so this file could never apply to a database
--    that had not already been pushed. A migration must stand on the migrations before it, not on a
--    push that happens to run afterwards.
ALTER TABLE "visit" ADD COLUMN IF NOT EXISTS "invoice_id" text;
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "visit_invoice_id_unique_idx"
  ON "visit" ("invoice_id") WHERE "invoice_id" IS NOT NULL;
