// Customer portal — public surface. Templates import from '../shared' (vendored copy of this package).
export { PortalProvider, usePortal, API_URL as PORTAL_API_URL } from './PortalContext'
export type { PortalContextValue } from './PortalContext'
export { PortalLayout, useVisibleSections } from './PortalLayout'
export { PortalDashboard } from './PortalDashboard'
export { PortalQuotes, PortalQuoteDetail } from './PortalQuotes'
export { PortalInvoices, PortalInvoiceDetail } from './PortalInvoices'
export { PortalPaymentMethods } from './PortalPaymentMethods'
export { PortalMessages } from './PortalMessages'
export { PortalProjects, PortalProjectDetail } from './PortalProjects'
export { PortalChangeOrders, PortalChangeOrderDetail } from './PortalChangeOrders'
export { PortalSelections } from './PortalSelections'
export { PortalMyJobs, PortalLienWaivers, PortalSubmittalReview, PortalAssignedRfis, PortalSharedDocuments } from './PortalCollaborators'
export { PortalProjectFiles } from './PortalProjectFiles'
export { PortalEquipment, PortalEquipmentDetail, PortalAgreements, PortalServiceRequest } from './PortalService'
export { SignaturePad, SignatureModal, SignatureDisplay } from './SignaturePad'
export { PortalPaymentForm, PortalPaymentModal } from './PaymentForm'
export type { PortalConfig, PortalSection, PortalRole } from './types'
export { DEFAULT_CLIENT_NAV, DEFAULT_COLLABORATOR_NAV, DEFAULT_REVIEWER_NAV, resolvePortalConfig } from './types'
