/**
 * fetch-fonts.ts — self-host the template's default web fonts (OFL-licensed)
 * so first paint never waits on a third-party stylesheet and the display
 * face can be preloaded (no layout shift on font swap).
 *
 * Downloads the LATIN woff2 subsets from the Google Fonts CSS API and writes:
 *   build/fonts/<Family>-<weight><i?>.woff2
 *   build/styles/fonts.css   (@font-face rules, font-display: swap)
 *
 *   bun scripts/fetch-fonts.ts
 * Re-run only when changing the default families. Commit the output.
 */
import fs from 'fs'
import path from 'path'

const ROOT = path.resolve(import.meta.dir, '..')
const fontsDir = path.join(ROOT, 'build', 'fonts')
fs.mkdirSync(fontsDir, { recursive: true })

const FAMILIES: Array<{ family: string; spec: string }> = [
  { family: 'Limelight', spec: 'Limelight' },
  { family: 'Cinzel', spec: 'Cinzel:wght@400;600;700;900' },
  { family: 'Cinzel Decorative', spec: 'Cinzel+Decorative:wght@400;700;900' },
  { family: 'Lora', spec: 'Lora:wght@400;600' },   // italics are synthesized — the italic face was the last CLS culprit
  { family: 'Special Elite', spec: 'Special+Elite' },
]
// A modern Chrome UA gets woff2 + unicode-range subsets.
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0 Safari/537.36'

const rules: string[] = []
const seenUrl_all = new Map<string, { file: string; weights: string[] }>()
for (const f of FAMILIES) {
  const seenUrl = new Map<string, { file: string; weights: string[] }>()
  const css = await (await fetch(`https://fonts.googleapis.com/css2?family=${f.spec}&display=swap`, { headers: { 'User-Agent': UA } })).text()
  // Split into @font-face blocks, keep only the /* latin */ ones.
  const blocks = css.split('@font-face').slice(1)
  for (let i = 0; i < blocks.length; i++) {
    const prev = i === 0 ? css.split('@font-face')[0] : blocks[i - 1]
    const isLatin = /\/\*\s*latin\s*\*\/\s*$/.test(prev)
    const b = blocks[i]
    if (!isLatin) continue
    const style = /font-style:\s*(\w+)/.exec(b)?.[1] || 'normal'
    const weight = /font-weight:\s*(\d+)/.exec(b)?.[1] || '400'
    const url = /url\((https:[^)]+\.woff2)\)/.exec(b)?.[1]
    const range = /unicode-range:\s*([^;]+);/.exec(b)?.[1]?.trim()
    if (!url) continue
    // Variable fonts come back as the SAME file for every weight — one file, a weight range.
    const dup = seenUrl.get(url)
    if (dup) { dup.weights.push(weight); continue }
    const file = `${f.family.replace(/ /g, '')}-${weight}${style === 'italic' ? 'i' : ''}.woff2`
    const buf = Buffer.from(await (await fetch(url)).arrayBuffer())
    fs.writeFileSync(path.join(fontsDir, file), buf)
    seenUrl.set(url, { file, weights: [weight] }); seenUrl_all.set(url, seenUrl.get(url)!)
    rules.push(`@font-face { font-family: '${f.family}'; font-style: ${style}; font-weight: __W_${url}__; font-display: swap; src: url('/fonts/${file}') format('woff2');${range ? ` unicode-range: ${range};` : ''} }`)
    console.log('saved', file, buf.length, 'bytes')
  }
}
// Fill in weight ranges for deduped (variable) files.
for (let i = 0; i < rules.length; i++) {
  rules[i] = rules[i].replace(/__W_(.+?)__/, (_m, url) => { const e = seenUrl_all.get(url)!; const ws = e.weights.map(Number); return ws.length > 1 ? `${Math.min(...ws)} ${Math.max(...ws)}` : String(ws[0]) })
}
const header = `/* Self-hosted web fonts (SIL Open Font License). Generated by scripts/fetch-fonts.ts — do not edit by hand. */\n`
fs.writeFileSync(path.join(ROOT, 'build', 'styles', 'fonts.css'), header + rules.join('\n') + '\n')
fs.writeFileSync(path.join(fontsDir, 'LICENSE.txt'), 'Limelight, Cinzel, Lora and Special Elite are licensed under the SIL Open Font License 1.1 (https://scripts.sil.org/OFL). Files fetched from Google Fonts for self-hosting.\n')
console.log('wrote build/styles/fonts.css with', rules.length, 'faces')
