/**
 * Twomiah Care — AES-256-GCM field-level encryption
 *
 * Used for SSN and driver's license numbers stored in the database.
 * Node.js built-in `crypto` module — no extra dependencies required.
 *
 * ENCRYPTION_KEY is auto-generated by Render on first deploy.
 * Back it up immediately — losing it means losing access to all
 * encrypted fields.
 *
 * Stored format:  "<iv_hex>:<authTag_hex>:<ciphertext_hex>"
 * Algorithm:      AES-256-GCM (authenticated encryption, tamper-evident)
 * Key:            32 bytes derived from ENCRYPTION_KEY env var
 */

import { createCipheriv, createDecipheriv, randomBytes, createHash } from 'crypto'

const ALGORITHM = 'aes-256-gcm'

function getKey(): Buffer {
  const raw = process.env.ENCRYPTION_KEY
  if (!raw) {
    throw new Error(
      'ENCRYPTION_KEY environment variable is not set. ' +
      'Cannot encrypt/decrypt sensitive fields.'
    )
  }
  if (/^[0-9a-fA-F]{64}$/.test(raw)) {
    return Buffer.from(raw, 'hex')
  }
  return createHash('sha256').update(raw).digest()
}

export function encrypt(plaintext: string | null | undefined): string | null {
  if (plaintext == null || plaintext === '') return null

  const key = getKey()
  const iv = randomBytes(12)
  const cipher = createCipheriv(ALGORITHM, key, iv)

  const ciphertext = Buffer.concat([
    cipher.update(String(plaintext), 'utf8'),
    cipher.final(),
  ])
  const authTag = cipher.getAuthTag()

  return [
    iv.toString('hex'),
    authTag.toString('hex'),
    ciphertext.toString('hex'),
  ].join(':')
}

export function decrypt(ciphertext: string | null | undefined): string | null {
  if (ciphertext == null || ciphertext === '') return null

  try {
    const parts = ciphertext.split(':')
    if (parts.length !== 3) return null

    const [ivHex, authTagHex, encHex] = parts
    const key = getKey()
    const iv = Buffer.from(ivHex, 'hex')
    const authTag = Buffer.from(authTagHex, 'hex')
    const enc = Buffer.from(encHex, 'hex')

    const decipher = createDecipheriv(ALGORITHM, key, iv)
    decipher.setAuthTag(authTag)

    return Buffer.concat([
      decipher.update(enc),
      decipher.final(),
    ]).toString('utf8')
  } catch {
    return null
  }
}

export function maskedDecrypt(ciphertext: string | null, visibleChars = 4): string {
  const plain = decrypt(ciphertext)
  if (!plain) return '\u2014'
  const digits = plain.replace(/\D/g, '')
  const visible = digits.slice(-visibleChars)
  return `${'*'.repeat(Math.max(0, digits.length - visibleChars))}${visible}`
}
