import { useState, useEffect } from 'react';
import { formatDate } from '../utils/date';
import { FileText, Calendar, DollarSign, RefreshCw, Plus, Eye, Clock, CheckCircle, AlertTriangle, XCircle } from 'lucide-react';
import api from '../services/api';
import { useToast } from '../contexts/ToastContext';
import { Button } from '../components/ui/DataTable';
import { Modal } from '../components/ui/Modal';

const filingStatusColors: Record<string, string> = {
  draft: 'bg-gray-100 text-gray-600',
  pending: 'bg-yellow-100 text-yellow-700',
  submitted: 'bg-blue-100 text-blue-700',
  accepted: 'bg-green-100 text-green-700',
  rejected: 'bg-red-100 text-red-700',
  amended: 'bg-purple-100 text-purple-700',
  calculated: 'bg-sky-100 text-sky-700 dark:bg-sky-900/40 dark:text-sky-200',
  filed: 'bg-green-100 text-green-700 dark:bg-green-900/40 dark:text-green-200',
  confirmed: 'bg-green-100 text-green-700 dark:bg-green-900/40 dark:text-green-200',
  superseded: 'bg-gray-200 text-gray-600 dark:bg-slate-700 dark:text-slate-300',
};

/** A filing that has been SUBMITTED has to stay exactly as it was filed. */
const canSupersede = (status: string) => !['filed', 'confirmed', 'superseded'].includes(String(status || '').toLowerCase());

/** filing_data is jsonb; the detail endpoint returns it whole alongside its aliased columns. */
const filingData = (f: any): any => {
  if (!f) return {};
  const d = f.filing_data ?? f.filingData;
  if (!d) return {};
  if (typeof d === 'string') { try { return JSON.parse(d); } catch { return {}; } }
  return d;
};

export default function TaxFilingPage() {
  const toast = useToast();
  const [tab, setTab] = useState('filings');

  // Filings
  const [filings, setFilings] = useState<any[]>([]);
  const [loadingFilings, setLoadingFilings] = useState(true);
  const [generateModal, setGenerateModal] = useState(false);
  const [generateForm, setGenerateForm] = useState({ type: 'state_excise', period: 'monthly', startDate: '', endDate: '' });
  const [generating, setGenerating] = useState(false);

  // Detail
  const [detailModal, setDetailModal] = useState(false);
  const [detailFiling, setDetailFiling] = useState<any>(null);
  const [detailLoading, setDetailLoading] = useState(false);

  // Setting a filing aside. The server has done this since T48 and there was no way to ask for it,
  // so a return generated by mistake stayed on the list as a current return. (T49 M1)
  const [supersedeFor, setSupersedeFor] = useState<any>(null);
  const [supersedeReason, setSupersedeReason] = useState('');
  const [superseding, setSuperseding] = useState(false);

  // Upcoming
  const [deadlines, setDeadlines] = useState<any[]>([]);
  const [loadingDeadlines, setLoadingDeadlines] = useState(true);

  // Summary
  const [summary, setSummary] = useState<any>(null);
  const [loadingSummary, setLoadingSummary] = useState(true);

  useEffect(() => {
    if (tab === 'filings') loadFilings();
    if (tab === 'upcoming') loadDeadlines();
    if (tab === 'summary') loadSummary();
  }, [tab]);

  const loadFilings = async () => {
    setLoadingFilings(true);
    try {
      const data = await api.get('/api/tax-filing/filings');
      setFilings(Array.isArray(data) ? data : data?.data || []);
    } catch (err) {
      toast.error('Failed to load filings');
    } finally {
      setLoadingFilings(false);
    }
  };

  const loadDeadlines = async () => {
    setLoadingDeadlines(true);
    try {
      const data = await api.get('/api/tax-filing/deadlines');
      setDeadlines(Array.isArray(data) ? data : data?.data || []);
    } catch (err) {
      toast.error('Failed to load deadlines');
    } finally {
      setLoadingDeadlines(false);
    }
  };

  const loadSummary = async () => {
    setLoadingSummary(true);
    try {
      const data = await api.get('/api/tax-filing/summary');
      setSummary(data);
    } catch (err) {
      toast.error('Failed to load tax summary');
    } finally {
      setLoadingSummary(false);
    }
  };

  const handleGenerate = async () => {
    if (!generateForm.startDate || !generateForm.endDate) {
      toast.error('Date range is required');
      return;
    }
    setGenerating(true);
    try {
      await api.post('/api/tax-filing/filings/generate', generateForm);
      toast.success('Filing generated');
      setGenerateModal(false);
      setGenerateForm({ type: 'state_excise', period: 'monthly', startDate: '', endDate: '' });
      loadFilings();
    } catch (err: any) {
      toast.error(err.message || 'Failed to generate filing');
    } finally {
      setGenerating(false);
    }
  };

  const doSupersede = async () => {
    const reason = supersedeReason.trim();
    // The server refuses an empty reason, so say so here rather than send a request that cannot work.
    if (!reason) { toast.error('Say why this filing is being set aside'); return; }
    setSuperseding(true);
    try {
      await api.put(`/api/tax-filing/filings/${supersedeFor.id}/supersede`, { reason });
      toast.success('Filing set aside');
      setSupersedeFor(null);
      setSupersedeReason('');
      setDetailModal(false);
      loadFilings();
    } catch (err: any) {
      // A submitted filing cannot be set aside, and the server explains why in a sentence worth showing.
      toast.error(err.message || 'Failed to set the filing aside');
    } finally {
      setSuperseding(false);
    }
  };

  const viewDetail = async (filing: any) => {
    setDetailFiling(filing);
    setDetailModal(true);
    setDetailLoading(true);
    try {
      const data = await api.get(`/api/tax-filing/filings/${filing.id}`);
      setDetailFiling(data);
    } catch (err) {
      toast.error('Failed to load filing detail');
    } finally {
      setDetailLoading(false);
    }
  };

  const tabs = [
    { id: 'filings', label: 'Filings', icon: FileText },
    { id: 'upcoming', label: 'Upcoming', icon: Calendar },
    { id: 'summary', label: 'Summary', icon: DollarSign },
  ];

  return (
    <div>
      <div className="flex items-center justify-between mb-6">
        <div>
          <h1 className="text-2xl font-bold text-gray-900 dark:text-slate-100">Tax Filing</h1>
          <p className="text-gray-600 dark:text-slate-400">Automated cannabis tax filing and reporting</p>
        </div>
      </div>

      {/* Tabs */}
      <div className="flex gap-1 mb-6 border-b">
        {tabs.map(t => (
          <button
            key={t.id}
            onClick={() => setTab(t.id)}
            className={`flex items-center gap-2 px-4 py-3 text-sm font-medium border-b-2 transition-colors ${
              tab === t.id
                ? 'border-green-600 text-green-700 dark:text-green-300'
                : 'border-transparent text-gray-500 dark:text-slate-300 hover:text-gray-700 dark:hover:text-slate-200'
            }`}
          >
            <t.icon className="w-4 h-4" />
            {t.label}
          </button>
        ))}
      </div>

      {/* Filings Tab */}
      {tab === 'filings' && (
        <div>
          <div className="flex justify-end mb-4">
            <Button onClick={() => setGenerateModal(true)}>
              <Plus className="w-4 h-4 mr-2 inline" />
              Generate Filing
            </Button>
          </div>

          {loadingFilings ? (
            <div className="flex items-center justify-center h-32">
              <div className="w-6 h-6 border-2 border-green-500 border-t-transparent rounded-full animate-spin" />
            </div>
          ) : (
            <div className="bg-white rounded-lg shadow-sm overflow-hidden dark:bg-slate-900">
              <table className="w-full">
                <thead className="bg-gray-50 dark:bg-slate-900">
                  <tr>
                    <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase dark:text-slate-400">Type</th>
                    <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase dark:text-slate-400">Period</th>
                    <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase dark:text-slate-400">Date Range</th>
                    <th className="px-4 py-3 text-right text-xs font-medium text-gray-500 uppercase dark:text-slate-400">Amount</th>
                    <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase dark:text-slate-400">Status</th>
                    <th className="px-4 py-3 text-right text-xs font-medium text-gray-500 uppercase dark:text-slate-400">Actions</th>
                  </tr>
                </thead>
                <tbody className="divide-y">
                  {filings.map(filing => (
                    <tr key={filing.id} className="hover:bg-gray-50">
                      <td className="px-4 py-3 font-medium text-gray-900 dark:text-slate-100">
                        {(filing.type || '').replace(/_/g, ' ').replace(/\b\w/g, (c: string) => c.toUpperCase())}
                      </td>
                      <td className="px-4 py-3 text-sm text-gray-600 capitalize dark:text-slate-400">{filing.period || '—'}</td>
                      <td className="px-4 py-3 text-sm text-gray-600 dark:text-slate-400">
                        {filing.startDate ? formatDate(filing.startDate) : '—'} - {filing.endDate ? formatDate(filing.endDate) : '—'}
                      </td>
                      <td className="px-4 py-3 text-right font-medium text-gray-900 dark:text-slate-100">
                        {filing.totalAmount != null ? `$${Number(filing.totalAmount).toLocaleString(undefined, { minimumFractionDigits: 2 })}` : '—'}
                      </td>
                      <td className="px-4 py-3">
                        <span className={`px-2 py-0.5 text-xs font-medium rounded-full ${filingStatusColors[filing.status] || 'bg-gray-100 text-gray-600'}`}>
                          {filing.status || 'draft'}
                        </span>
                      </td>
                      <td className="px-4 py-3 text-right">
                        <button onClick={() => viewDetail(filing)} className="text-sm text-green-600 hover:text-green-700 dark:hover:text-green-300 flex items-center gap-1 ml-auto">
                          <Eye className="w-3 h-3" /> View
                        </button>
                      </td>
                    </tr>
                  ))}
                  {filings.length === 0 && (
                    <tr>
                      <td colSpan={6} className="px-4 py-12 text-center text-gray-500 dark:text-slate-400">
                        <FileText className="w-12 h-12 mx-auto mb-3 text-gray-300" />
                        <p>No tax filings yet</p>
                        <p className="text-sm mt-1">Generate your first filing to get started</p>
                      </td>
                    </tr>
                  )}
                </tbody>
              </table>
            </div>
          )}
        </div>
      )}

      {/* Upcoming Tab */}
      {tab === 'upcoming' && (
        <div>
          {loadingDeadlines ? (
            <div className="flex items-center justify-center h-32">
              <div className="w-6 h-6 border-2 border-green-500 border-t-transparent rounded-full animate-spin" />
            </div>
          ) : (
            <div className="space-y-3">
              {deadlines.map((deadline, i) => {
                const dueDate = new Date(deadline.dueDate);
                const daysUntil = Math.ceil((dueDate.getTime() - Date.now()) / 86400000);
                const isOverdue = daysUntil < 0;
                const isUrgent = daysUntil >= 0 && daysUntil <= 7;

                return (
                  <div key={deadline.id || i} className="bg-white rounded-lg shadow-sm p-5 border border-gray-100 flex items-center justify-between dark:bg-slate-900">
                    <div className="flex items-center gap-4">
                      <div className={`w-10 h-10 rounded-lg flex items-center justify-center ${
                        isOverdue ? 'bg-red-100' : isUrgent ? 'bg-orange-100' : 'bg-green-100'
                      }`}>
                        <Calendar className={`w-5 h-5 ${isOverdue ? 'text-red-600' : isUrgent ? 'text-orange-600' : 'text-green-600'}`} />
                      </div>
                      <div>
                        <p className="font-medium text-gray-900 dark:text-slate-100">
                          {(deadline.type || '').replace(/_/g, ' ').replace(/\b\w/g, (c: string) => c.toUpperCase())}
                        </p>
                        <p className="text-sm text-gray-500 dark:text-slate-400">{deadline.description || deadline.period || '—'}</p>
                      </div>
                    </div>
                    <div className="text-right">
                      <p className="font-medium text-gray-900 dark:text-slate-100">{dueDate.toLocaleDateString()}</p>
                      <p className={`text-sm ${isOverdue ? 'text-red-600 font-medium' : isUrgent ? 'text-orange-600' : 'text-gray-500 dark:text-slate-400'}`}>
                        {isOverdue ? `${Math.abs(daysUntil)} days overdue` : daysUntil === 0 ? 'Due today' : `${daysUntil} days left`}
                      </p>
                    </div>
                  </div>
                );
              })}
              {deadlines.length === 0 && (
                <div className="text-center py-12 text-gray-500 dark:text-slate-400">
                  <Calendar className="w-12 h-12 mx-auto mb-3 text-gray-300" />
                  <p>No upcoming deadlines</p>
                </div>
              )}
            </div>
          )}
        </div>
      )}

      {/* Summary Tab */}
      {tab === 'summary' && (
        <div>
          {loadingSummary ? (
            <div className="flex items-center justify-center h-32">
              <div className="w-6 h-6 border-2 border-green-500 border-t-transparent rounded-full animate-spin" />
            </div>
          ) : (
            <div className="space-y-6">
              {/* YTD Stats */}
              <div className="grid md:grid-cols-3 gap-4">
                <div className="bg-white rounded-lg shadow-sm p-6 border border-gray-100 dark:bg-slate-900">
                  <div className="flex items-center gap-3 mb-2">
                    <div className="w-10 h-10 bg-green-100 rounded-lg flex items-center justify-center">
                      <DollarSign className="w-5 h-5 text-green-600" />
                    </div>
                    <p className="text-sm text-gray-500 dark:text-slate-400">Total Collected (YTD)</p>
                  </div>
                  <p className="text-2xl font-bold text-gray-900 dark:text-slate-100">
                    ${Number(summary?.totalCollected || 0).toLocaleString(undefined, { minimumFractionDigits: 2 })}
                  </p>
                </div>
                <div className="bg-white rounded-lg shadow-sm p-6 border border-gray-100 dark:bg-slate-900">
                  <div className="flex items-center gap-3 mb-2">
                    <div className="w-10 h-10 bg-blue-100 rounded-lg flex items-center justify-center">
                      <CheckCircle className="w-5 h-5 text-blue-600" />
                    </div>
                    <p className="text-sm text-gray-500 dark:text-slate-400">Total Filed (YTD)</p>
                  </div>
                  <p className="text-2xl font-bold text-gray-900 dark:text-slate-100">
                    ${Number(summary?.totalFiled || 0).toLocaleString(undefined, { minimumFractionDigits: 2 })}
                  </p>
                </div>
                <div className="bg-white rounded-lg shadow-sm p-6 border border-gray-100 dark:bg-slate-900">
                  <div className="flex items-center gap-3 mb-2">
                    <div className="w-10 h-10 bg-orange-100 rounded-lg flex items-center justify-center">
                      <AlertTriangle className="w-5 h-5 text-orange-600" />
                    </div>
                    <p className="text-sm text-gray-500 dark:text-slate-400">Outstanding</p>
                  </div>
                  <p className="text-2xl font-bold text-gray-900 dark:text-slate-100">
                    ${Number(summary?.outstanding || 0).toLocaleString(undefined, { minimumFractionDigits: 2 })}
                  </p>
                </div>
              </div>

              {/* Chart placeholder */}
              <div className="bg-white rounded-lg shadow-sm p-6 border border-gray-100 dark:bg-slate-900">
                <h3 className="font-semibold text-gray-900 mb-4 dark:text-slate-100">Tax Collection Trends</h3>
                <div className="h-64 flex items-center justify-center bg-gray-50 rounded-lg dark:bg-slate-900">
                  <div className="text-center text-gray-500 dark:text-slate-400">
                    <DollarSign className="w-12 h-12 mx-auto mb-2" />
                    <p className="text-sm">Chart visualization will be displayed here</p>
                  </div>
                </div>
              </div>

              {/* Breakdown */}
              {summary?.breakdown && Array.isArray(summary.breakdown) && summary.breakdown.length > 0 && (
                <div className="bg-white rounded-lg shadow-sm overflow-hidden border border-gray-100 dark:bg-slate-900">
                  <div className="px-6 py-4 border-b">
                    <h3 className="font-semibold text-gray-900 dark:text-slate-100">Tax Breakdown by Type</h3>
                  </div>
                  <table className="w-full">
                    <thead className="bg-gray-50 dark:bg-slate-900">
                      <tr>
                        <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase dark:text-slate-400">Tax Type</th>
                        <th className="px-4 py-3 text-right text-xs font-medium text-gray-500 uppercase dark:text-slate-400">Collected</th>
                        <th className="px-4 py-3 text-right text-xs font-medium text-gray-500 uppercase dark:text-slate-400">Filed</th>
                        <th className="px-4 py-3 text-right text-xs font-medium text-gray-500 uppercase dark:text-slate-400">Outstanding</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y">
                      {summary.breakdown.map((row: any, i: number) => (
                        <tr key={i} className="hover:bg-gray-50">
                          <td className="px-4 py-3 font-medium text-gray-900 dark:text-slate-100">{row.type || '—'}</td>
                          <td className="px-4 py-3 text-right text-gray-700 dark:text-slate-200">${Number(row.collected || 0).toFixed(2)}</td>
                          <td className="px-4 py-3 text-right text-gray-700 dark:text-slate-200">${Number(row.filed || 0).toFixed(2)}</td>
                          <td className="px-4 py-3 text-right font-medium text-orange-600">${Number(row.outstanding || 0).toFixed(2)}</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              )}
            </div>
          )}
        </div>
      )}

      {/* Generate Filing Modal */}
      <Modal
        isOpen={generateModal}
        onClose={() => setGenerateModal(false)}
        title="Generate Tax Filing"
      >
        <div className="space-y-4">
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1 dark:text-slate-200">Filing Type</label>
            <select
              value={generateForm.type}
              onChange={(e) => setGenerateForm({ ...generateForm, type: e.target.value })}
              className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-green-500 focus:border-green-500 text-gray-900 dark:border-slate-700 dark:text-slate-100"
            >
              <option value="state_excise">State Excise Tax</option>
              <option value="local_excise">Local Excise Tax</option>
              <option value="sales_tax">Sales Tax</option>
              <option value="city_tax">City Tax</option>
            </select>
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1 dark:text-slate-200">Period</label>
            <select
              value={generateForm.period}
              onChange={(e) => setGenerateForm({ ...generateForm, period: e.target.value })}
              className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-green-500 focus:border-green-500 text-gray-900 dark:border-slate-700 dark:text-slate-100"
            >
              <option value="monthly">Monthly</option>
              <option value="quarterly">Quarterly</option>
              <option value="annual">Annual</option>
            </select>
          </div>
          <div className="grid grid-cols-2 gap-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1 dark:text-slate-200">Start Date *</label>
              <input
                type="date"
                value={generateForm.startDate}
                onChange={(e) => setGenerateForm({ ...generateForm, startDate: e.target.value })}
                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-green-500 focus:border-green-500 text-gray-900 dark:border-slate-700 dark:text-slate-100"
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1 dark:text-slate-200">End Date *</label>
              <input
                type="date"
                value={generateForm.endDate}
                onChange={(e) => setGenerateForm({ ...generateForm, endDate: e.target.value })}
                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-green-500 focus:border-green-500 text-gray-900 dark:border-slate-700 dark:text-slate-100"
              />
            </div>
          </div>
        </div>
        <div className="flex justify-end gap-3 mt-6">
          <button onClick={() => setGenerateModal(false)} className="px-4 py-2 text-gray-700 hover:bg-gray-100 rounded-lg font-medium dark:text-slate-200">Cancel</button>
          <Button onClick={handleGenerate} disabled={generating}>
            {generating ? 'Generating...' : 'Generate'}
          </Button>
        </div>
      </Modal>

      {/* Filing Detail Modal */}
      <Modal
        isOpen={detailModal}
        onClose={() => setDetailModal(false)}
        title="Filing Detail"
      >
        {detailLoading ? (
          <div className="flex items-center justify-center h-32">
            <div className="w-6 h-6 border-2 border-green-500 border-t-transparent rounded-full animate-spin" />
          </div>
        ) : detailFiling ? (
          <div className="space-y-4">
            <div className="grid grid-cols-2 gap-4 text-sm">
              <div>
                <p className="text-gray-500 dark:text-slate-400">Type</p>
                <p className="font-medium text-gray-900 dark:text-slate-100">{(detailFiling.type || '').replace(/_/g, ' ').replace(/\b\w/g, (c: string) => c.toUpperCase())}</p>
              </div>
              <div>
                <p className="text-gray-500 dark:text-slate-400">Status</p>
                <span className={`px-2 py-0.5 text-xs font-medium rounded-full ${filingStatusColors[detailFiling.status] || 'bg-gray-100 text-gray-600'}`}>
                  {detailFiling.status || 'draft'}
                </span>
              </div>
              <div>
                <p className="text-gray-500 dark:text-slate-400">Period</p>
                <p className="font-medium text-gray-900 capitalize dark:text-slate-100">{detailFiling.period}</p>
              </div>
              <div>
                <p className="text-gray-500 dark:text-slate-400">Total Amount</p>
                <p className="font-medium text-gray-900 dark:text-slate-100">
                  ${Number(detailFiling.totalAmount || 0).toLocaleString(undefined, { minimumFractionDigits: 2 })}
                </p>
              </div>
            </div>

            {/* What the return works out at, and whether it reconciles.
                The server has computed effectiveRate, expectedAtRate and collectedVariance since
                T47 P5 precisely so the person signing can see the division an auditor will do
                first — and none of it was on screen. (T49 M1) */}
            {(() => {
              const d = filingData(detailFiling);
              if (d.effectiveRate == null && d.taxableSales == null) return null;
              const reconciles = d.reconciles;
              return (
                <div className="rounded-lg border p-3 text-sm dark:border-slate-700">
                  <div className="grid grid-cols-2 gap-3">
                    <div>
                      <p className="text-gray-500 dark:text-slate-400">Taxable base</p>
                      <p className="font-medium text-gray-900 tabular-nums dark:text-slate-100">
                        ${Number(d.taxableSales || 0).toLocaleString(undefined, { minimumFractionDigits: 2 })}
                      </p>
                      {d.taxableBasis && <p className="mt-0.5 text-xs text-gray-500 dark:text-slate-400">{d.taxableBasis}</p>}
                    </div>
                    <div>
                      <p className="text-gray-500 dark:text-slate-400">Works out at</p>
                      <p className="font-medium text-gray-900 tabular-nums dark:text-slate-100">{Number(d.effectiveRate || 0).toFixed(2)}%</p>
                      {d.expectedAtRate != null && (
                        <p className="mt-0.5 text-xs text-gray-500 dark:text-slate-400">
                          ${Number(d.expectedAtRate).toLocaleString(undefined, { minimumFractionDigits: 2 })} at the configured rate
                        </p>
                      )}
                    </div>
                  </div>
                  {reconciles === false && d.reconcileNote && (
                    <p className="mt-3 flex gap-2 rounded-md bg-amber-50 p-2 text-amber-900 dark:bg-amber-900/30 dark:text-amber-100">
                      <AlertTriangle className="mt-0.5 h-4 w-4 shrink-0" />
                      <span>{d.reconcileNote}</span>
                    </p>
                  )}
                  {reconciles === true && (
                    <p className="mt-3 flex items-center gap-2 text-green-700 dark:text-green-300">
                      <CheckCircle className="h-4 w-4 shrink-0" />
                      The excise collected matches the configured rate.
                    </p>
                  )}
                </div>
              );
            })()}

            {/* Orders out of step.
                The reconcile note above says in so many words that the orders are "listed under
                'orders out of step'" — and there was no such section anywhere in the product. This
                is it. (T49 M1) */}
            {(() => {
              const orders = filingData(detailFiling).varianceOrders;
              if (!Array.isArray(orders) || orders.length === 0) return null;
              return (
                <div>
                  <h4 className="mb-2 text-sm font-medium text-gray-700 dark:text-slate-200">Orders out of step</h4>
                  <p className="mb-2 text-xs text-gray-500 dark:text-slate-400">
                    These sales took a different amount of excise from the configured rate. They are the ones to check first —
                    a rate changed mid-period, a sale rung up before the rate was set, or an order written in by an integration.
                  </p>
                  {/* Field names read from the server, not guessed: orderNumber / date /
                      taxableBase / exciseTaken / exciseExpected / difference. */}
                  <div className="overflow-x-auto rounded-lg border dark:border-slate-700">
                    <table className="w-full text-sm">
                      <thead className="bg-gray-50 dark:bg-slate-900">
                        <tr>
                          <th className="px-3 py-2 text-left text-xs font-medium text-gray-500 dark:text-slate-400">Order</th>
                          <th className="px-3 py-2 text-left text-xs font-medium text-gray-500 dark:text-slate-400">Date</th>
                          <th className="px-3 py-2 text-right text-xs font-medium text-gray-500 dark:text-slate-400">Base</th>
                          <th className="px-3 py-2 text-right text-xs font-medium text-gray-500 dark:text-slate-400">Excise taken</th>
                          <th className="px-3 py-2 text-right text-xs font-medium text-gray-500 dark:text-slate-400">At the rate</th>
                          <th className="px-3 py-2 text-right text-xs font-medium text-gray-500 dark:text-slate-400">Difference</th>
                        </tr>
                      </thead>
                      <tbody className="divide-y dark:divide-slate-700">
                        {orders.map((o: any, i: number) => (
                          <tr key={o.orderNumber || i}>
                            <td className="px-3 py-2 font-medium text-gray-900 dark:text-slate-100">{o.orderNumber || '—'}</td>
                            <td className="px-3 py-2 text-gray-600 dark:text-slate-300">{o.date ? formatDate(o.date) : '—'}</td>
                            <td className="px-3 py-2 text-right tabular-nums text-gray-700 dark:text-slate-200">${Number(o.taxableBase || 0).toFixed(2)}</td>
                            <td className="px-3 py-2 text-right tabular-nums text-gray-900 dark:text-slate-100">${Number(o.exciseTaken || 0).toFixed(2)}</td>
                            <td className="px-3 py-2 text-right tabular-nums text-gray-500 dark:text-slate-400">${Number(o.exciseExpected || 0).toFixed(2)}</td>
                            <td className={`px-3 py-2 text-right tabular-nums font-medium ${Number(o.difference || 0) < 0 ? 'text-red-600 dark:text-red-400' : 'text-amber-700 dark:text-amber-300'}`}>
                              {Number(o.difference || 0) > 0 ? '+' : ''}{Number(o.difference || 0).toFixed(2)}
                            </td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                </div>
              );
            })()}

            {/* Line items */}
            {detailFiling.lineItems && Array.isArray(detailFiling.lineItems) && detailFiling.lineItems.length > 0 && (
              <div>
                <h4 className="text-sm font-medium text-gray-700 mb-2 dark:text-slate-200">Line Items</h4>
                <div className="border rounded-lg overflow-hidden">
                  <table className="w-full text-sm">
                    <thead className="bg-gray-50 dark:bg-slate-900">
                      <tr>
                        <th className="px-3 py-2 text-left text-xs font-medium text-gray-500 dark:text-slate-400">Description</th>
                        <th className="px-3 py-2 text-right text-xs font-medium text-gray-500 dark:text-slate-400">Amount</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y">
                      {detailFiling.lineItems.map((item: any, i: number) => (
                        <tr key={i}>
                          <td className="px-3 py-2 text-gray-700 dark:text-slate-200">{item.description || item.name || `Item ${i + 1}`}</td>
                          <td className="px-3 py-2 text-right text-gray-900 dark:text-slate-100">${Number(item.amount || 0).toFixed(2)}</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>
            )}
          </div>
        ) : null}
        <div className="mt-6 flex items-center justify-between gap-3">
          {/* Setting a return aside is a manager's job and the server records the reason against
              it. A SUBMITTED return has to stay as it was filed, so the action is simply not
              offered for one — the server refuses it too, and says why. */}
          {detailFiling && canSupersede(detailFiling.status) ? (
            <button
              onClick={() => { setSupersedeFor(detailFiling); setSupersedeReason(''); }}
              className="rounded-lg px-4 py-2 font-medium text-red-700 hover:bg-red-50 dark:text-red-300 dark:hover:bg-red-900/30"
            >
              Set aside…
            </button>
          ) : <span className="text-xs text-gray-500 dark:text-slate-400">
            {detailFiling && String(detailFiling.status).toLowerCase() === 'superseded'
              ? 'This return has been set aside.'
              : detailFiling ? 'A submitted return stays as it was filed — generate an amended one for the same period instead.' : ''}
          </span>}
          <button onClick={() => setDetailModal(false)} className="px-4 py-2 text-gray-700 hover:bg-gray-100 rounded-lg font-medium dark:text-slate-200">Close</button>
        </div>
      </Modal>

      {/* Set a filing aside — the reason is required and is recorded against the return. (T49 M1) */}
      <Modal isOpen={!!supersedeFor} onClose={() => setSupersedeFor(null)} title="Set this filing aside">
        <div className="space-y-3">
          <p className="text-sm text-gray-600 dark:text-slate-300">
            It stays on the list and keeps its figures — it stops counting as the current return for
            {supersedeFor ? ` ${formatDate(supersedeFor.startDate)} – ${formatDate(supersedeFor.endDate)}` : ' this period'}.
          </p>
          <div>
            <label className="mb-1 block text-sm font-medium text-gray-700 dark:text-slate-200">Why is it being set aside?</label>
            <textarea
              value={supersedeReason}
              onChange={(e) => setSupersedeReason(e.target.value)}
              rows={3}
              maxLength={500}
              autoFocus
              placeholder="Generated by mistake, replaced by a corrected run, wrong period…"
              className="w-full rounded-lg border px-3 py-2 text-sm dark:border-slate-700 dark:bg-slate-900 dark:text-slate-100"
            />
            <p className="mt-1 text-xs text-gray-500 dark:text-slate-400">Recorded against the return, so the next person can see why.</p>
          </div>
        </div>
        <div className="mt-6 flex justify-end gap-2">
          <button onClick={() => setSupersedeFor(null)} className="rounded-lg px-4 py-2 font-medium text-gray-700 hover:bg-gray-100 dark:text-slate-200">Cancel</button>
          <Button onClick={doSupersede} disabled={superseding || !supersedeReason.trim()}>
            {superseding ? 'Setting aside…' : 'Set aside'}
          </Button>
        </div>
      </Modal>
    </div>
  );
}
