// CI guard: a server feature an owner is supposed to USE has a screen.
//
// ── why this guard exists ───────────────────────────────────────────────────────────────────────
//
// Asked for by name, as one of three rules meant to close whole families of findings rather than
// individual paths. T49 M1: five features shipped in T48 that exist only in the API — supersede a
// filing, the reconciliation variance list, End of Day's awaitingCollection, delivery-zone overlap
// warnings, and the online-awaiting count. The reconciliation note even tells the owner the orders
// are "listed under 'orders out of step'", a section that does not exist. Lifting a recall is the
// same: the rule works, and a recalled batch has no button on the Batches page for any role.
//
// Each was a real fix. None is reachable by the person it was written for, so from the shop's point
// of view none of them shipped.
//
// ── how it works, and what it deliberately does NOT do ──────────────────────────────────────────
//
// Each entry pairs a server capability with something the front end must mention for it to be
// reachable — a path, a field name, a label. That is a weak test on its own: a screen can reference
// a field and still be useless. It is not trying to prove the screen is good; it is trying to stop a
// capability shipping with NO screen at all, which is the thing that keeps happening.
//
// The OUTSTANDING list is the honest part. Those five are known to be API-only right now and are
// recorded here by name, with the finding that reported them, so nobody has to rediscover them and
// nobody can quietly add a sixth. Moving one out of OUTSTANDING and into COVERED is what "we built
// the screen" looks like to this guard.
//
//   bun scripts/check-server-features-have-screens.ts
import { readFileSync, existsSync, readdirSync } from 'node:fs'
import { join } from 'node:path'
const ROOT = new URL('../', import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, '$1')

const FE = 'templates/crm-dispensary/frontend/src'
let failed = 0
const fail = (m: string) => { failed++; console.error(`FAIL: ${m}`) }

/**
 * Source with comments removed.
 *
 * This matters more here than anywhere. The first version of this guard asked "does the UI mention
 * this string anywhere", and a mutation run showed EIGHT of thirteen removals sailing through: the
 * "orders out of step" heading could be renamed and the guard stayed green because the COMMENT
 * above it explaining why the heading is worded that way still contained the phrase. A rule about
 * what the product does must not be satisfiable by prose describing it — least of all prose I
 * wrote. (Same lesson as #169 grepping for "FOR UPDATE" and finding it on the wrong table.)
 */
const code = (src: string) => src
  .replace(/\/\*[\s\S]*?\*\//g, '')
  .replace(/(^|[^:])\/\/[^\n]*/g, '$1')

/** Every front-end source file of a template, concatenated, comments stripped. */
function frontendSource(base: string): string {
  const out: string[] = []
  const walk = (rel: string) => {
    const dir = join(ROOT, base, rel)
    if (!existsSync(dir)) return
    for (const e of readdirSync(dir, { withFileTypes: true })) {
      if (e.isDirectory()) { walk(join(rel, e.name)); continue }
      if (!/\.(tsx?|jsx?)$/.test(e.name)) continue
      try { out.push(code(readFileSync(join(dir, e.name), 'utf8'))) } catch { /* unreadable is not mentioned */ }
    }
  }
  walk('.')
  return out.join('\n')
}
const ui = frontendSource(FE)
if (!ui) fail(`${FE} has no readable source — this guard cannot answer anything`)

/** Capabilities that MUST be reachable from a screen. */
const COVERED: Array<{ what: string; needles: RegExp[]; why: string }> = [
  {
    what: 'two-factor at sign-in',
    needles: [/mfaRequired/, /completeMfa/],
    why: 'T49 H4: login returns a challenge instead of tokens. Without a code step on the sign-in page, an account with two-factor on cannot sign in at all — the fix would lock people out rather than protect them.',
  },
  {
    what: 'recovery codes at sign-in',
    needles: [/recoveryCodesAvailable|recovery code/i],
    why: 'T49 H4: the codes the product generates have to be typeable somewhere, which was the tester\'s point.',
  },
  // ── the six T49 M1 findings, built ────────────────────────────────────────────────────────────
  //
  // Every needle below pins WIRING, not wording. A label can be renamed and a section can be hidden
  // behind `false &&` while the words stay in the file — the first mutation run of this guard had
  // eight removals pass for exactly that reason. So each entry names the API call that performs the
  // action, or the CONDITION that decides whether the reader ever sees it.
  {
    what: 'setting a tax filing aside',
    needles: [/filings\/\$\{[^}]+\}\/supersede/, /setSupersedeFor\(detailFiling\)/],
    why: 'T49 M1: the server has done this since T48 and nothing could ask for it, so a return generated by mistake stayed on the list as the current one. Pinned on the PUT and on the control that opens it.',
  },
  {
    what: 'the excise variance list',
    needles: [/filingData\(detailFiling\)\.varianceOrders/, /Orders out of step/],
    why: 'T49 M1: the reconcile note tells the owner the orders are "listed under \'orders out of step\'" — a section that did not exist. The heading is pinned verbatim because the note points at it by name, and it is now matched in CODE with comments stripped.',
  },
  {
    what: "End of Day's outstanding figures",
    needles: [/\(report\.unsettledSales \|\| 0\) > 0/, /\(report\.awaitingCollection \|\| 0\) > 0/, /report\.awaitingCollectionTotal/],
    why: 'T49 M1 and T47 N1: both were on the response and neither on the report a manager closes the day with. The CONDITIONS are pinned, not the field names — a field can still be referenced while the section is switched off.',
  },
  {
    what: 'delivery-zone overlap warnings',
    needles: [/\{zone\.overlapWarning && \(/],
    why: 'T49 M1: zones already overlapping when the rule arrived still are, the server reports it on every zone, and nothing showed it — so checkout quoted whichever fee matched first and nobody could see why.',
  },
  {
    what: 'the online-awaiting order count',
    needles: [/orderMix\?\.online_awaiting_count/, /setOrderMix\(orders\)/],
    why: 'T49 M1: added so "Online: 0" beside a list of online orders would stop reading as broken — it had been filed twice. The figure shipped and the panel did not, so it read as broken a third time.',
  },
  {
    what: 'lifting a recall from the Batches page',
    needles: [/setLiftFor\(detail\)/, /batches\/\$\{[^}]+\}\/activate`, \{ reason \}/],
    why: 'T49 M1: the server has accepted a lift with a written reason since T48 Q6, and the page said "No actions available for recalled batches". Pinned on the control and on the POST that carries the reason.',
  },
]
for (const cap of COVERED) {
  const missing = cap.needles.filter((n) => !n.test(ui))
  if (missing.length) fail(`${cap.what} has no screen — the front end never mentions ${missing.map(String).join(' or ')}. ${cap.why}`)
}

/**
 * Known API-only, recorded so they are not rediscovered and a seventh cannot be added quietly.
 *
 * The six T49 M1 findings that used to sit here have all been BUILT and are now in COVERED above,
 * which is what "we built the screen" looks like to this guard. The list is empty on purpose rather
 * than deleted: it is where the next one goes, and the check below still asserts the list is
 * honest — anything recorded here that has in fact gained a screen must move, rather than sit here
 * understating the product.
 */
const OUTSTANDING: Array<{ what: string; needle: RegExp; finding: string }> = []
const builtSince: string[] = []
for (const item of OUTSTANDING) {
  if (item.needle.test(ui)) builtSince.push(`${item.what} (${item.finding})`)
}
if (builtSince.length) {
  fail(`these are listed as API-only but the front end now references them — move them to COVERED so the guard protects them: ${builtSince.join(', ')}`)
}

// ── the same rule, in crm-salon ──────────────────────────────────────────────────────────────────
//
// The rule is not the dispensary's. The salon had TWO tables it could not reach: it owned `expense`
// with no create, no screen and a read endpoint that answered 500 on every call it ever received;
// and /api/payroll/summary reported on `time_entry` while nothing in the whole product could write
// one — no clock-in, no entry form, no screen. A report on a table that is always empty is not a
// feature. Both are the shared modules four other templates have mounted for a long time.
{
  const SALON = 'templates/crm-salon'
  const salonUi = frontendSource(`${SALON}/frontend/src`)
  if (!salonUi) fail(`${SALON}/frontend/src has no readable source`)

  const backend = (rel: string) => { try { return readFileSync(join(ROOT, SALON, rel), 'utf8') } catch { return '' } }
  const index = backend('backend/src/index.ts')

  // A page FILE existing is not a screen. The first version of this check matched the component
  // name anywhere in the front end, which the page's own file satisfies — so deleting the route
  // left the guard green and the feature unreachable. Three things make it a screen: the server
  // mounts it, App.tsx ROUTES it, and the sidebar carries it.
  const app = code(readFileSync(join(ROOT, SALON, 'frontend/src/App.tsx'), 'utf8'))
  const shell = code(readFileSync(join(ROOT, SALON, 'frontend/src/shellConfig.ts'), 'utf8'))
  for (const [what, mount, routeFile, component, why] of [
    ['expenses', "app.route('/api/expenses', expensesRoutes)", 'backend/src/routes/expenses.ts', 'ExpensesPage',
      'the salon owned the expense table and could not record one'],
    ['time', "app.route('/api/time', timeRoutes)", 'backend/src/routes/time.ts', 'TimePage',
      'payroll reported on time_entry and nothing in the product could write one'],
  ] as Array<[string, string, string, string, string]>) {
    if (!code(index).includes(mount)) fail(`crm-salon does not mount ${what} at ${mount} — ${why}`)
    if (!backend(routeFile)) fail(`crm-salon is missing ${routeFile}`)
    if (!new RegExp(`import ${component} from './pages/${component}'`).test(app))
      fail(`crm-salon's App.tsx does not import ${component} — ${why}`)
    if (!new RegExp(`<Route path="${what}" element=\\{<${component} />\\} />`).test(app))
      fail(`crm-salon has a ${component} that is never routed — the file exists and no URL reaches it`)
    if (!new RegExp(`to: '/crm/${what}'`).test(shell))
      fail(`crm-salon has a ${what} screen with no sidebar entry — it is only reachable by typing the URL`)
  }
  /**
   * …and the rule applies to what the SHARED module grows, not only to what a template mounts.
   *
   * The expense repayment (RR8/X6) is a server capability written for a salon owner: money handed
   * back on a claim that was paid too much. The refusal on a reimbursed expense NAMES it — "record
   * what came back with Record repayment on this expense" — so if the control ever goes, the product
   * starts telling people to use something that is not there, which is the exact shape of the T49 M1
   * family this guard exists for.
   *
   * Pinned on the POST that performs it and on the control that opens the dialog, not on the words.
   */
  const shared = frontendSource('packages/tenant-ui/src')
  for (const [what, needle, why] of [
    ['recording a repayment', /expenses\/\$\{[^}]+\}\/\$\{path\}`/,
      'the 409 on a reimbursed expense tells the reader to use it'],
    ['…its control', /label: 'Correct an over-payment'/,
      'a POST with nothing that opens it is an API, not a feature'],
    ['…and the choice that decides whether the money is back or owed', /repayForm\.settled \? 'repayment' : 'overpayment'/,
      'RR9: one control, two outcomes. Without the choice, half the feature is unreachable'],
    ['…and what came back is visible on the row', /money\(repaid\(row\)\)/,
      'a repayment nobody can see on the sheet leaves the total unexplained'],
    // ── the staff balance (RR9) ───────────────────────────────────────────────────────────────
    ['the owed-by-staff panel', /api\.get\('\/api\/expenses\/owed'\)/,
      'a receivable nobody can see is a receivable nobody chases'],
    ['…and settling it', /expenses\/owed\/\$\{settleFor\.userId\}\/settle`/,
      'four routes on the server and no control is an API, not a feature'],
    ['the pay run', /api\.get\('\/api\/payroll\/summary'/,
      'RR9: /api/payroll/summary had existed in five CRMs with no screen anywhere, and a deduction recovered from pay MUST be visible on the pay run or the money is recovered twice'],
    ['…showing what was recovered', /money\(u\.deductions\)/,
      'the deduction is the reason the pay run had to be built'],
  ] as Array<[string, RegExp, string]>) {
    if (!needle.test(shared)) fail(`${what} has no screen in packages/tenant-ui — ${why}`)
  }

  // …and the half-broken duplicate it replaced must not come back.
  const payroll = backend('backend/src/routes/payroll.ts')
  if (/app\.get\('\/expenses'/.test(payroll)) {
    fail('crm-salon payroll.ts has a second expenses endpoint again — one table, one implementation. That duplication is how the hourly-rate defect happened in this very file (T46 N24).')
  }
}

if (failed) { console.error(`\nserver features have screens: ${failed} check(s) FAILED`); process.exit(1) }
console.log(`server features have screens: ${COVERED.length} capability(ies) reachable from a screen; ${OUTSTANDING.length} recorded as API-only and still API-only`)
