/**
 * Concatenates every SQL file in apps/api/migrations/ in chronological order
 * into a single blob, plus the migration tail of apps/api/schema.sql, so the
 * user can paste it once into the Supabase SQL Editor. All files in here use
 * IF NOT EXISTS / IF EXISTS guards so running this against a partially-
 * migrated database is safe.
 *
 *   bun run scripts/bundle-migrations.ts > /tmp/twomiah-migrations.sql
 */
import * as fs from 'fs'
import * as path from 'path'
import { fileURLToPath } from 'url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const migrationsDir = path.join(__dirname, '..', 'migrations')

const files = fs.readdirSync(migrationsDir)
  .filter(f => f.endsWith('.sql'))
  .sort()

const out: string[] = []
out.push('-- Twomiah Factory: bundled migrations')
out.push('-- Generated by scripts/bundle-migrations.ts on ' + new Date().toISOString())
out.push('-- Safe to re-run: every statement uses IF NOT EXISTS / IF EXISTS guards.')
out.push('')

for (const f of files) {
  out.push('-- ─── ' + f + ' ' + '─'.repeat(Math.max(0, 60 - f.length)))
  out.push(fs.readFileSync(path.join(migrationsDir, f), 'utf8').trim())
  out.push('')
}

process.stdout.write(out.join('\n'))
