// crm-dispensary — GET /api/qr-scanner/analytics answered 500 on the live tenant.
//
// Found by a fleet-wide sweep of every parameterless GET across all ten test tenants (620 endpoints);
// it was the only unexplained 5xx in the fleet, and it is on the vertical with the launch bar. An
// earlier root-only sweep had missed it, because the fault is on a sub-path.
//
// Two sibling handlers in the same file answer 200 — /analytics/stats and /analytics/top-scanned —
// so this is not "the QR module is broken". The difference is that this one GROUPs BY `storeDay(...)`,
// which embeds the timezone as a BOUND PARAMETER: drizzle emits `AT TIME ZONE $1` in the SELECT list
// and `$2` in the GROUP BY, Postgres does not consider those the same expression, and the whole query
// is rejected. A store-day grouping is exactly the kind of fix that looks safe and is not.
import { Hono } from 'hono'
import { setupSchema } from './setup.ts'
import { db } from './db/index.ts'

let failed = 0, passed = 0
const check = (name: string, ok: boolean, detail?: unknown) => {
  if (ok) { passed++; console.log(`  ok   ${name}`) }
  else { failed++; console.log(`  FAIL ${name}`, detail === undefined ? '' : JSON.stringify(detail)?.slice(0, 500)) }
}

await setupSchema()
const { company, user, product } = await import('./db/schema.ts')

const [co] = await db.insert(company).values({
  name: 'QR Analytics', slug: 'qr-analytics', email: 'qra@test.local', state: 'OH',
  enabledFeatures: ['products', 'batches', 'reports'],
} as any).returning()
const [owner] = await db.insert(user).values({
  email: 'owner-qra@test.local', passwordHash: 'x', firstName: 'O', lastName: 'W', role: 'owner', companyId: co.id,
} as any).returning()
const [prod] = await db.insert(product).values({
  companyId: co.id, name: 'Analytics Probe Flower', category: 'flower', price: '25',
} as any).returning()

const app = new Hono()
app.route('/api/qr-scanner', (await import('./src/routes/qr-scanner.ts')).default)
app.onError((await import('./src/utils/errors.ts')).errorHandler)
const api = async (path: string) => {
  const res = await app.request(path, { headers: { 'x-test-user': owner.id } })
  const t = await res.text(); let j: any = t; try { j = JSON.parse(t) } catch {}
  return { status: res.status, json: j, text: t }
}

// Some scan events to aggregate, spread over days so the day bucketing has something to do.
// Inserted through drizzle rather than raw SQL: `id` is generated by a $defaultFn in the schema, not
// by a database default, so a raw INSERT leaves it null and the not-null constraint fires.
const { qrScanEvent } = await import('./db/schema.ts')
await db.insert(qrScanEvent).values(
  Array.from({ length: 6 }, (_, i) => ({
    companyId: co.id, entityType: 'product', entityId: prod.id, context: 'inventory',
    scannedBy: owner.id, createdAt: new Date(Date.now() - i * 86400000),
  })) as any,
)

// ══════════ the three analytics reads ═══════════════════════════════════════════════════════════
{
  const bare = await api('/api/qr-scanner/analytics')
  check('GET /analytics answers — it was 500 on the live tenant', bare.status === 200,
    { status: bare.status, body: bare.text?.slice(0, 400) })
  if (bare.status === 200) {
    check('…and buckets the scans by the store\'s day', Array.isArray(bare.json?.scansByDay) && bare.json.scansByDay.length > 0,
      bare.json?.scansByDay)
    check('…with every bucket a date and a count', (bare.json?.scansByDay || []).every((r: any) => /^\d{4}-\d{2}-\d{2}/.test(String(r.date)) && Number(r.count) > 0),
      bare.json?.scansByDay)
    check('…and the six scans are all accounted for',
      (bare.json?.scansByDay || []).reduce((s: number, r: any) => s + Number(r.count || 0), 0) === 6,
      bare.json?.scansByDay)
    check('…and the totals agree', Number(bare.json?.totals?.total_scans) === 6, bare.json?.totals)
    check('…and the hourly heatmap is there', Array.isArray(bare.json?.scanHeatmap) && bare.json.scanHeatmap.length > 0, bare.json?.scanHeatmap)
    check('…and the product it scanned is named', (bare.json?.topProducts || []).some((p: any) => p.product_name === 'Analytics Probe Flower'), bare.json?.topProducts)
  }
}
{
  // The two siblings answered 200 live; pinned here so a fix to the one above cannot break them.
  const stats = await api('/api/qr-scanner/analytics/stats')
  check('GET /analytics/stats still answers', stats.status === 200, { status: stats.status, body: stats.text?.slice(0, 200) })
  check('…and counts all six scans', Number(stats.json?.allTime) === 6, stats.json)
  const top = await api('/api/qr-scanner/analytics/top-scanned')
  check('GET /analytics/top-scanned still answers', top.status === 200, { status: top.status, body: top.text?.slice(0, 200) })
}

console.log(`\n  ${passed} passed, ${failed} failed`)
process.exit(failed ? 1 : 0)
