// crm-dispensary — T48 Q8, and the tester's answer on the P5 reconciliation note.
//
// P5 follow-up. Asked whether "reconciles: false" was useful, the tester said: "Mostly. The sentence
//    is clear, and a clean day proves it can reconcile. But a shop owner can't find 'orders created
//    outside the register' alone. List the orders charged below the rate, with order number, date
//    and excise taken, and the note becomes something they can act on." Correct — the note named a
//    variance and then handed the owner a haystack to find it in.
//
// Q8. A filing generated by mistake could not be voided or marked superseded. Immutable is the right
//    instinct for a tax record, but it was being used to mean "nothing can ever be said about it",
//    and the result is a list where three filings from one afternoon of testing sit beside the real
//    ones looking exactly as authoritative.
import { Hono } from 'hono'
import { sql } from 'drizzle-orm'
import { setupSchema } from './setup.ts'
import { db } from './db/index.ts'
import { company, user, contact, product } from './db/schema.ts'

// The SHOP's day, not UTC's. These companies are in Ohio, so the tax day runs on
// America/New_York (T52): between UTC midnight and the shop's midnight, `new Date().toISOString()`
// names TOMORROW in shop terms, the filing covers a window holding none of the orders completed a
// moment earlier, and every figure comes back 0. Red for four hours a night, green the rest of the
// time — which is how this class of failure gets dismissed as flakiness.
const shopDay = (offsetDays = 0) =>
  new Date(Date.now() + offsetDays * 86400000).toLocaleDateString('en-CA', { timeZone: 'America/New_York' })

let failed = 0, passed = 0
const check = (name: string, ok: boolean, detail?: unknown) => {
  if (ok) { passed++; console.log(`  ok   ${name}`) }
  else { failed++; console.log(`  FAIL ${name}`, detail === undefined ? '' : JSON.stringify(detail)?.slice(0, 320)) }
}

await setupSchema()

const [co] = await db.insert(company).values({
  name: 'Twomiah Leaf', slug: 'leaf-t48tx', email: 'tx48@test.local', state: 'OH',
  exciseTaxRate: '15', salesTaxRate: '0',
  enabledFeatures: ['products', 'orders', 'compliance', 'tax_filing'],
} as any).returning()
const [owner] = await db.insert(user).values({
  email: 'owner-t48tx@test.local', passwordHash: 'x', firstName: 'O', lastName: 'U', role: 'owner', companyId: co.id,
} as any).returning()
const [adult] = await db.insert(contact).values({ name: 'Addie Adult', type: 'customer', companyId: co.id } as any).returning()
const [flower] = await db.insert(product).values({
  name: 'Blue Dream', companyId: co.id, category: 'flower', price: '100', weightGrams: '3.5',
  stockQuantity: 500, taxCategory: 'cannabis', trackInventory: true,
} as any).returning()

const app = new Hono()
app.route('/api/orders', (await import('./src/routes/orders.ts')).default)
app.route('/api/tax-filing', (await import('./src/routes/tax-filing.ts')).default)
app.onError((await import('./src/utils/errors.ts')).errorHandler)

const api = async (method: string, path: string, body?: unknown) => {
  const res = await app.request(path, {
    method,
    headers: { 'content-type': 'application/json', 'x-test-user': owner.id, 'x-test-company': co.id, 'x-test-role': 'owner' },
    body: body === undefined ? undefined : JSON.stringify(body),
  })
  const t = await res.text(); let j: any = t; try { j = JSON.parse(t) } catch {}
  return { status: res.status, json: j }
}
const rows = async (q: any) => { const r: any = await db.execute(q); return (r.rows || r) as any[] }
const today = shopDay()
const sell = async () => {
  const r = await api('POST', '/api/orders', { items: [{ productId: flower.id, quantity: 1 }], orderType: 'walk_in', contactId: adult.id })
  const id = (r.json?.data || r.json)?.id
  await db.execute(sql`UPDATE orders SET status = 'completed', completed_at = NOW() WHERE id = ${id}`)
  return id
}
const generate = async () => {
  const f = await api('POST', '/api/tax-filing/filings/generate', { filingType: 'excise_tax', periodStart: today, periodEnd: today })
  const raw = f.json?.filing_data ?? f.json?.filingData
  return { res: f, id: f.json?.id, data: typeof raw === 'string' ? JSON.parse(raw) : raw }
}

// ── a clean period names nobody ─────────────────────────────────────────────────────────────────
{
  await sell(); await sell()
  const { data } = await generate()
  check('P5: a clean period reconciles', data?.reconciles === true, { reconciles: data?.reconciles, variance: data?.collectedVariance })
  check('P5: …and lists no orders, because there is nothing to chase',
    Array.isArray(data?.varianceOrders) && data.varianceOrders.length === 0, data?.varianceOrders)
}

// ── and one that does not, names the orders ─────────────────────────────────────────────────────
//
// One sale is rewritten to have taken $5.00 of excise on a $100 base — the shape of a sale rung up
// before the rate was configured, or an order written straight in by an integration. That is what
// the owner has to be able to find, and what "check orders created outside the register" did not
// help them find at all.
{
  const strayId = await sell()
  await db.execute(sql`UPDATE orders SET excise_tax = '5.00' WHERE id = ${strayId}`)
  const [stray] = await rows(sql`SELECT number FROM orders WHERE id = ${strayId}`)

  const { data } = await generate()
  check('Q/P5: the return no longer reconciles', data?.reconciles === false, { reconciles: data?.reconciles, variance: data?.collectedVariance })

  const list = data?.varianceOrders || []
  check('P5: …and the orders out of step are listed', list.length === 1, list)

  const row = list[0]
  check('P5: …by order number, which is what the owner searches on', row?.orderNumber === stray?.number, { got: row?.orderNumber, want: stray?.number })
  check('P5: …with the date', row?.date === today, row?.date)
  check('P5: …the excise actually taken', Math.round(Number(row?.exciseTaken) * 100) === 500, row?.exciseTaken)
  check('P5: …what it should have been at the configured rate', Math.round(Number(row?.exciseExpected) * 100) === 1500, row?.exciseExpected)
  check('P5: …and the difference, signed so under- and over-collection read differently',
    Math.round(Number(row?.difference) * 100) === -1000, row?.difference)
  check('P5: …and the list adds up to the variance on the return',
    Math.abs(Number(data?.collectedVariance) - list.reduce((s: number, r: any) => s + Number(r.difference), 0)) < 0.011,
    { variance: data?.collectedVariance, sum: list.reduce((s: number, r: any) => s + Number(r.difference), 0) })

  check('P5: …and the note points at the list instead of describing a haystack',
    /out of step/i.test(String(data?.reconcileNote)) && !/created outside the register/i.test(String(data?.reconcileNote)),
    data?.reconcileNote)
}

// ── Q8: a filing generated by mistake can be set aside ──────────────────────────────────────────
{
  const { id } = await generate()
  check('Q8: a filing exists to set aside', !!id, id)

  const bare = await api('PUT', `/api/tax-filing/filings/${id}/supersede`, {})
  check('Q8: superseding without a reason is refused', bare.status === 400, { status: bare.status, body: bare.json })
  check('Q8: …named, so a screen can ask for one', bare.json?.code === 'supersede_needs_reason', bare.json)
  check('Q8: …and the refusal suggests what a reason looks like',
    /generated by mistake|wrong period|corrected run/i.test(String(bare.json?.error)), bare.json?.error)

  const done = await api('PUT', `/api/tax-filing/filings/${id}/supersede`, { reason: 'Generated by mistake while testing' })
  check('Q8: …and with a reason it is set aside', done.status === 200, { status: done.status, body: done.json })

  const [row] = await rows(sql`SELECT status, notes, total_tax_due FROM tax_filings WHERE id = ${id}`)
  check('Q8: the row is marked superseded', row?.status === 'superseded', row?.status)
  check('Q8: …the reason is kept on it', /Generated by mistake while testing/.test(String(row?.notes)), row?.notes)
  check('Q8: …dated, because "when did this stop being current" is the next question',
    new RegExp(`Superseded ${today}`).test(String(row?.notes)), row?.notes)
  check('Q8: …and the FIGURES are untouched — the record is kept, not edited',
    Number(row?.total_tax_due) > 0, row?.total_tax_due)

  const again = await api('PUT', `/api/tax-filing/filings/${id}/supersede`, { reason: 'again' })
  check('Q8: …and it cannot be superseded twice', again.status === 400 && again.json?.code === 'already_superseded', again.json)

  // It must not be submittable afterwards — that is the whole point of setting it aside.
  const filed = await api('PUT', `/api/tax-filing/filings/${id}/file`, { confirmationNumber: 'STATE-123' })
  check('Q8: a superseded filing cannot then be submitted', filed.status === 400, { status: filed.status, body: filed.json })
  check('Q8: …and says to generate a fresh one', /generate a fresh filing/i.test(String(filed.json?.error)), filed.json?.error)
  check('Q8: …and it is still superseded, not filed',
    (await rows(sql`SELECT status FROM tax_filings WHERE id = ${id}`))[0]?.status === 'superseded')
}

// ── but a filing that really was submitted stays submitted ──────────────────────────────────────
//
// Setting that one aside is rewriting history rather than recording it. The honest move is an
// amended filing for the same period, and the refusal says so.
{
  const { id } = await generate()
  const filed = await api('PUT', `/api/tax-filing/filings/${id}/file`, { confirmationNumber: 'STATE-456' })
  check('Q8: a filing can be submitted', filed.status === 200, { status: filed.status, body: filed.json })

  const sup = await api('PUT', `/api/tax-filing/filings/${id}/supersede`, { reason: 'changed my mind' })
  check('Q8: a SUBMITTED filing cannot be set aside', sup.status === 400, { status: sup.status, body: sup.json })
  check('Q8: …named as already filed', sup.json?.code === 'already_filed', sup.json)
  check('Q8: …and told to amend instead, which is the real remedy',
    /amended filing/i.test(String(sup.json?.error)), sup.json?.error)
  check('Q8: …and it is still filed', (await rows(sql`SELECT status FROM tax_filings WHERE id = ${id}`))[0]?.status === 'filed')
}

console.log(`\n  ${passed} passed, ${failed} failed`)
process.exit(failed ? 1 : 0)
